spring:
  application:
    name: order_service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.syamsundar.order_service.*"
        spring.json.type.mapping: >
            stock-reserved-event: com.syamsundar.order_service.kafka.event.StockReservedEvent