version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: flashsale-postgres
    environment:
      POSTGRES_DB: flashsale
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  product-service:
    build: .
    container_name: product-service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/flashsale
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres