spring:
  application:
    name: product-service

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis

logging:
  level:
    org.springframework.cache: TRACE
    org.springframework.data.redis: DEBUG